# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.10


stages:
    - test

pytest:
    stage: test
    script:
        - pip install -r requirements.txt
        - pip install -U pytest
        - python3 -m pytest -q tests/test_part1.py
        - python3 -m pytest -q tests/test_part2.py
    rules:
        - if: $CI_COMMIT_REF_NAME == "master"
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH == "master"
        - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

